-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Seed data for IPCM-TSU. Values flagged is_placeholder are stand-ins until the institute confirms them.

insert into public.states (name) values
  ('Abia'),
  ('Adamawa'),
  ('Akwa Ibom'),
  ('Anambra'),
  ('Bauchi'),
  ('Bayelsa'),
  ('Benue'),
  ('Borno'),
  ('Cross River'),
  ('Delta'),
  ('Ebonyi'),
  ('Edo'),
  ('Ekiti'),
  ('Enugu'),
  ('FCT'),
  ('Gombe'),
  ('Imo'),
  ('Jigawa'),
  ('Kaduna'),
  ('Kano'),
  ('Katsina'),
  ('Kebbi'),
  ('Kogi'),
  ('Kwara'),
  ('Lagos'),
  ('Nasarawa'),
  ('Niger'),
  ('Ogun'),
  ('Ondo'),
  ('Osun'),
  ('Oyo'),
  ('Plateau'),
  ('Rivers'),
  ('Sokoto'),
  ('Taraba'),
  ('Yobe'),
  ('Zamfara')
on conflict do nothing;

-- Taraba LGAs now; full national LGA list is imported in Phase 1.
insert into public.lgas (state_id, name)
select s.id, l.name from public.states s, (values ('Ardo Kola'), ('Bali'), ('Donga'), ('Gashaka'), ('Gassol'), ('Ibi'), ('Jalingo'), ('Karim Lamido'), ('Kurmi'), ('Lau'), ('Sardauna'), ('Takum'), ('Ussa'), ('Wukari'), ('Yorro'), ('Zing')) as l(name)
where s.name = 'Taraba'
on conflict do nothing;

-- PCM: Certificate in Peace and Conflict Management
insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)
values ('PCM', 'peace-conflict-management', 'Certificate in Peace and Conflict Management', 'Peace and Conflict Management', 'Understand why conflicts start, how they escalate, and how to resolve them.', 'The foundation course of the institute. Participants learn the language, frameworks and practical tools of peace and conflict work, grounded in Nigerian and African realities.', array['Anyone new to peace work', 'Public servants and community leaders', 'Graduates entering the field']::text[], array['Public service', 'Community and faith leaders', 'NGOs']::text[], array['Explain a conflict using recognised analytical frameworks', 'Choose an appropriate response for a given conflict', 'Communicate in ways that calm rather than escalate']::text[], 'A written analysis of a conflict the participant knows first-hand.', array['Five O''Level credits including English Language (WASSCE, NECO or equivalent), or', 'Age 25 or above with at least 2 years of relevant work or community experience.', 'Graduates and serving officers are welcome.']::text[], 8, true, 1, '/placeholders/programme-pcm.jpg', null)
on conflict (code) do nothing;
insert into public.modules (programme_id, number, title, summary)
select id, m.number, m.title, m.summary from public.programmes, (values
  (1, 'Foundations of peace and conflict studies', 'Concepts, types and levels of conflict; positive and negative peace.'),
  (2, 'Causes and dynamics of conflict in Nigeria', 'Identity, land, resources and politics; how conflicts escalate.'),
  (3, 'Conflict handling styles and communication for peace', 'Choosing a response; listening, framing and de-escalation.'),
  (4, 'African and indigenous approaches to resolution', 'Traditional institutions, elders, faith actors and restorative practice.')
) as m(number, title, summary) where code = 'PCM'
on conflict do nothing;
insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)
select id, 'application'::public.fee_type, 3500000, 30000 from public.programmes where code = 'PCM'
union all
select id, 'tuition'::public.fee_type, 10000000, 30000 from public.programmes where code = 'PCM'
on conflict do nothing;
insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)
select id, 'PCM – February 2027', '2027-02-06', '2027-03-27', '2027-01-31', 40, 'IPCM Lecture Hall, Taraba State University, Jalingo', 'open'
from public.programmes where code = 'PCM';

-- NMA: Certificate in Negotiation, Mediation and ADR
insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)
values ('NMA', 'negotiation-mediation-adr', 'Certificate in Negotiation, Mediation and ADR', 'Negotiation, Mediation and ADR', 'Lead negotiations and mediate disputes from first meeting to signed agreement.', 'A skills-intensive course built around role-play and simulated mediation. Participants practise every stage of a mediation, under observation, until it becomes second nature.', array['Traditional and religious leaders', 'Lawyers and HR professionals', 'Community and organisational leaders']::text[], array['Legal and HR', 'Community and faith leaders', 'Public service']::text[], array['Run a structured, interest-based negotiation', 'Conduct a mediation from opening to written agreement', 'Draft a clear, enforceable settlement']::text[], 'A graded, observed mediation simulation.', array['Five O''Level credits including English Language (WASSCE, NECO or equivalent), or', 'Age 25 or above with at least 2 years of relevant work or community experience.', 'Graduates and serving officers are welcome.']::text[], 8, true, 2, '/placeholders/programme-nma.jpg', null)
on conflict (code) do nothing;
insert into public.modules (programme_id, number, title, summary)
select id, m.number, m.title, m.summary from public.programmes, (values
  (1, 'Principles of negotiation', 'Interests versus positions, power, preparation and BATNA.'),
  (2, 'The mediation process and ethics', 'Opening, storytelling, issue mapping, options, agreement; neutrality and confidentiality.'),
  (3, 'ADR in Nigerian law and customary practice', 'Arbitration, conciliation, multi-door courthouses and customary dispute resolution.'),
  (4, 'Community, workplace and family mediation', 'Practicum: supervised simulations across common Nigerian dispute types.')
) as m(number, title, summary) where code = 'NMA'
on conflict do nothing;
insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)
select id, 'application'::public.fee_type, 3500000, 30000 from public.programmes where code = 'NMA'
union all
select id, 'tuition'::public.fee_type, 10000000, 30000 from public.programmes where code = 'NMA'
on conflict do nothing;
insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)
select id, 'NMA – February 2027', '2027-02-06', '2027-03-27', '2027-01-31', 40, 'IPCM Lecture Hall, Taraba State University, Jalingo', 'open'
from public.programmes where code = 'NMA';

-- CEW: Certificate in Conflict Analysis, Early Warning and Early Response
insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)
values ('CEW', 'conflict-analysis-early-warning', 'Certificate in Conflict Analysis, Early Warning and Early Response', 'Conflict Analysis and Early Warning', 'Spot conflict before it turns violent, and trigger the right response in time.', 'Participants learn to analyse conflict systematically, track warning signs, and work with security, government and traditional actors to act early.', array['Security agencies', 'Local government staff', 'NGO and community monitors']::text[], array['Security', 'Public service', 'NGOs']::text[], array['Produce a clear conflict analysis', 'Set up an indicator-based watch system', 'Escalate warnings to the right actors at the right time']::text[], 'An early-warning plan for a named LGA or community.', array['Five O''Level credits including English Language (WASSCE, NECO or equivalent), or', 'Age 25 or above with at least 2 years of relevant work or community experience.', 'Graduates and serving officers are welcome.']::text[], 8, true, 3, '/placeholders/programme-cew.jpg', null)
on conflict (code) do nothing;
insert into public.modules (programme_id, number, title, summary)
select id, m.number, m.title, m.summary from public.programmes, (values
  (1, 'Conflict analysis tools', 'Conflict mapping, stakeholder analysis and the conflict tree.'),
  (2, 'Early warning indicators and data', 'Choosing indicators, collecting reliable information, ethics.'),
  (3, 'Reporting, verification and digital monitoring', 'Verifying reports, avoiding rumour, using simple digital tools.'),
  (4, 'Designing early response', 'Coordinating with security, traditional and government actors.')
) as m(number, title, summary) where code = 'CEW'
on conflict do nothing;
insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)
select id, 'application'::public.fee_type, 3500000, 30000 from public.programmes where code = 'CEW'
union all
select id, 'tuition'::public.fee_type, 10000000, 30000 from public.programmes where code = 'CEW'
on conflict do nothing;
insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)
select id, 'CEW – February 2027', '2027-02-06', '2027-03-27', '2027-01-31', 40, 'IPCM Lecture Hall, Taraba State University, Jalingo', 'open'
from public.programmes where code = 'CEW';

-- PHR: Certificate in Peacebuilding, Humanitarian Response and Post-Conflict Recovery
insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)
values ('PHR', 'peacebuilding-humanitarian-recovery', 'Certificate in Peacebuilding, Humanitarian Response and Post-Conflict Recovery', 'Peacebuilding and Recovery', 'Help communities recover, reconcile and rebuild after violence.', 'For people working with communities affected by conflict and displacement. The course joins humanitarian principles with long-term peacebuilding and recovery.', array['NGO and humanitarian staff', 'IDP camp and SEMA officials', 'Social workers and faith-based responders']::text[], array['NGOs', 'Public service', 'Community and faith leaders']::text[], array['Apply humanitarian principles in practice', 'Design a reconciliation activity', 'Plan conflict-sensitive recovery work']::text[], 'A recovery or peacebuilding project design for an affected community.', array['Five O''Level credits including English Language (WASSCE, NECO or equivalent), or', 'Age 25 or above with at least 2 years of relevant work or community experience.', 'Graduates and serving officers are welcome.']::text[], 8, true, 4, '/placeholders/programme-phr.jpg', null)
on conflict (code) do nothing;
insert into public.modules (programme_id, number, title, summary)
select id, m.number, m.title, m.summary from public.programmes, (values
  (1, 'Peacebuilding theory and practice', 'From ceasefire to sustainable peace; local ownership.'),
  (2, 'Humanitarian principles and displacement', 'Managing IDPs and returnees with dignity and protection.'),
  (3, 'Trauma, reconciliation and transitional justice', 'Trauma awareness, dialogue and truth-telling.'),
  (4, 'Livelihoods, reintegration and recovery', 'Conflict-sensitive recovery and reintegration programmes.')
) as m(number, title, summary) where code = 'PHR'
on conflict do nothing;
insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)
select id, 'application'::public.fee_type, 3500000, 30000 from public.programmes where code = 'PHR'
union all
select id, 'tuition'::public.fee_type, 10000000, 30000 from public.programmes where code = 'PHR'
on conflict do nothing;
insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)
select id, 'PHR – February 2027', '2027-02-06', '2027-03-27', '2027-01-31', 40, 'IPCM Lecture Hall, Taraba State University, Jalingo', 'open'
from public.programmes where code = 'PHR';

-- PSS: Certificate in Peace and Security Studies
insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)
values ('PSS', 'peace-security-studies', 'Certificate in Peace and Security Studies', 'Peace and Security Studies', 'Connect security work to lasting peace, within human-rights standards.', 'For officers and those who work with them. The course links security practice to peace outcomes, with a focus on the conflicts most common in the North-East and Middle Belt.', array['Police, NSCDC and military officers', 'Vigilance and community security groups', 'Security advisers']::text[], array['Security']::text[], array['Analyse threats through a human-security lens', 'Strengthen trust between security agencies and communities', 'Act within human-rights standards']::text[], 'A policy brief on a security challenge in the participant’s area of operation.', array['Five O''Level credits including English Language (WASSCE, NECO or equivalent), or', 'Age 25 or above with at least 2 years of relevant work or community experience.', 'Graduates and serving officers are welcome.']::text[], 8, true, 5, '/placeholders/programme-pss.jpg', null)
on conflict (code) do nothing;
insert into public.modules (programme_id, number, title, summary)
select id, m.number, m.title, m.summary from public.programmes, (values
  (1, 'Human security and the Nigerian security architecture', 'Who does what, and how human security changes the question.'),
  (2, 'Civil-military and police-community relations', 'Building trust and cooperation with communities.'),
  (3, 'Farmer-herder, banditry and resource conflicts', 'Drivers, dynamics, and small arms and light weapons.'),
  (4, 'Human rights and conflict-sensitive operations', 'Rules of engagement, accountability and do-no-harm.')
) as m(number, title, summary) where code = 'PSS'
on conflict do nothing;
insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)
select id, 'application'::public.fee_type, 3500000, 30000 from public.programmes where code = 'PSS'
union all
select id, 'tuition'::public.fee_type, 10000000, 30000 from public.programmes where code = 'PSS'
on conflict do nothing;
insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)
select id, 'PSS – February 2027', '2027-02-06', '2027-03-27', '2027-01-31', 40, 'IPCM Lecture Hall, Taraba State University, Jalingo', 'open'
from public.programmes where code = 'PSS';

insert into public.site_settings (key, value, is_placeholder) values
  ('address', '"Institute of Peace and Conflict Management, Taraba State University, ATC, 660213, Jalingo, Taraba State, Nigeria"'::jsonb, false),
  ('email', '"ipcm@tsuniversity.edu.ng"'::jsonb, true),
  ('admissions_email', '"ipcm-admissions@tsuniversity.edu.ng"'::jsonb, true),
  ('phone', '"+234 800 000 0000"'::jsonb, true),
  ('whatsapp', '"+234 800 000 0000"'::jsonb, true),
  ('office_hours', '"Monday to Friday, 8:00am to 4:00pm; Saturdays during cohorts"'::jsonb, true),
  ('director_name', '"Director, IPCM"'::jsonb, true),
  ('venue', '"IPCM Lecture Hall, Taraba State University, Jalingo"'::jsonb, true),
  ('next_intake', '{"label":"February 2027 cohort","startDate":"2027-02-06","deadline":"2027-01-31","seats":40,"seatsLeft":40,"placeholder":true}'::jsonb, true),
  ('socials', '[]'::jsonb, true)
on conflict (key) do nothing;
