/**
 * Generates supabase/seed.sql from src/lib/programmes.ts and src/lib/site.ts,
 * so the website and the database always share one programme catalogue.
 * Run: npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from 'node:fs'
import { FEES, FORMAT, programmes } from '../src/lib/programmes'
import { site } from '../src/lib/site'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const arr = (a: string[]) => `array[${a.map(q).join(', ')}]::text[]`

const states = ['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','FCT','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara']
const tarabaLgas = ['Ardo Kola','Bali','Donga','Gashaka','Gassol','Ibi','Jalingo','Karim Lamido','Kurmi','Lau','Sardauna','Takum','Ussa','Wukari','Yorro','Zing']

let sql = `-- GENERATED by scripts/generate-seed.ts — do not edit by hand.\n-- Seed data for IPCM-TSU. Values flagged is_placeholder are stand-ins until the institute confirms them.\n\n`

sql += `insert into public.states (name) values\n${states.map((s) => `  (${q(s)})`).join(',\n')}\non conflict do nothing;\n\n`
sql += `-- Taraba LGAs now; full national LGA list is imported in Phase 1.\ninsert into public.lgas (state_id, name)\nselect s.id, l.name from public.states s, (values ${tarabaLgas.map((l) => `(${q(l)})`).join(', ')}) as l(name)\nwhere s.name = 'Taraba'\non conflict do nothing;\n\n`

programmes.forEach((p, i) => {
  sql += `-- ${p.code}: ${p.title}\n`
  sql += `insert into public.programmes (code, slug, title, short_title, promise, overview, audience, audience_tags, outcomes, capstone, entry_requirements, duration_weeks, is_published, sort_order, card_image_path, hero_image_path)\nvalues (${q(p.code)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.shortTitle)}, ${q(p.promise)}, ${q(p.overview)}, ${arr(p.audience)}, ${arr(p.audienceTags)}, ${arr(p.outcomes)}, ${q(p.capstone)}, ${arr(FORMAT.entry)}, ${FORMAT.durationWeeks}, true, ${i + 1}, ${q(`/placeholders/programme-${p.code.toLowerCase()}.jpg`)}, null)\non conflict (code) do nothing;\n`
  sql += `insert into public.modules (programme_id, number, title, summary)\nselect id, m.number, m.title, m.summary from public.programmes, (values\n${p.modules.map((m) => `  (${m.number}, ${q(m.title)}, ${q(m.summary)})`).join(',\n')}\n) as m(number, title, summary) where code = ${q(p.code)}\non conflict do nothing;\n`
  sql += `insert into public.fee_items (programme_id, type, base_amount_kobo, processing_fee_kobo)\nselect id, 'application'::public.fee_type, ${FEES.application.base}, ${FEES.application.processing} from public.programmes where code = ${q(p.code)}\nunion all\nselect id, 'tuition'::public.fee_type, ${FEES.tuition.base}, ${FEES.tuition.processing} from public.programmes where code = ${q(p.code)}\non conflict do nothing;\n`
  sql += `insert into public.cohorts (programme_id, name, start_date, end_date, application_deadline, capacity, venue, status)\nselect id, ${q(`${p.code} – February 2027`)}, '2027-02-06', '2027-03-27', '2027-01-31', 40, ${q(site.venue.value)}, 'open'\nfrom public.programmes where code = ${q(p.code)};\n\n`
})

const settings: [string, unknown, boolean][] = [
  ['address', site.address.value, site.address.placeholder],
  ['email', site.email.value, site.email.placeholder],
  ['admissions_email', site.admissionsEmail.value, site.admissionsEmail.placeholder],
  ['phone', site.phone.value, site.phone.placeholder],
  ['whatsapp', site.whatsapp.value, site.whatsapp.placeholder],
  ['office_hours', site.hours.value, site.hours.placeholder],
  ['director_name', site.director.name, true],
  ['venue', site.venue.value, site.venue.placeholder],
  ['next_intake', site.nextIntake, true],
  ['socials', [], true],
]
sql += `insert into public.site_settings (key, value, is_placeholder) values\n${settings.map(([k, v, p]) => `  (${q(k)}, ${q(JSON.stringify(v))}::jsonb, ${p})`).join(',\n')}\non conflict (key) do nothing;\n`

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log('Wrote supabase/seed.sql')
